language: php

cache:
  directories:
    - $HOME/.composer/cache

env:
  global:
    - COMPOSER_PROCESS_TIMEOUT=600
    - COMPOSER_ARGS="--no-interaction"
    - COVERAGE_DEPS="php-coveralls/php-coveralls"
    - LOWEST_DEPS_REMOVE="laminas/laminas-router"
    - LATEST_DEPS_REQUIRE="laminas/laminas-mvc-plugin-flashmessenger laminas/laminas-mvc-i18n laminas/laminas-mvc-console"

matrix:
  fast_finish: true
  include:
    - php: 7.3
      env:
        - DEPS=lowest
    - php: 7.3
      env:
        - DEPS=latest
        - CS_CHECK=true
        - TEST_COVERAGE=true
    - php: 7.4
      env:
        - DEPS=lowest
    - php: 7.4
      env:
        - DEPS=latest
    - php: 8.0
      env:
        - DEPS=lowest
        - COMPOSER_ARGS="--no-interaction --ignore-platform-reqs"
    - php: 8.0
      env:
        - DEPS=latest
        - COMPOSER_ARGS="--no-interaction --ignore-platform-reqs"

before_install:
  - if [[ $TEST_COVERAGE != 'true' ]]; then phpenv config-rm xdebug.ini || return 0 ; fi
  - if [[ $DEPS == 'lowest' ]]; then travis_retry composer remove $COMPOSER_ARGS --no-update --dev $LOWEST_DEPS_REMOVE ; fi
  - if [[ $DEPS == 'latest' ]]; then travis_retry composer require $COMPOSER_ARGS --no-update --dev $LATEST_DEPS_REQUIRE ; fi

install:
  - if [[ $DEPS == 'lowest' ]]; then travis_retry composer update $COMPOSER_ARGS --prefer-lowest ; fi
  - if [[ $DEPS == 'latest' ]]; then travis_retry composer update $COMPOSER_ARGS ; fi
  - if [[ $TEST_COVERAGE == 'true' ]]; then travis_retry composer require --dev $COMPOSER_ARGS $COVERAGE_DEPS ; fi
  - stty cols 120 && composer show

script:
  - if [[ $TEST_COVERAGE == 'true' ]]; then composer test-coverage ; else composer test ; fi
  - if [[ $CS_CHECK == 'true' ]]; then composer cs-check ; fi

after_script:
  - if [[ $TEST_COVERAGE == 'true' ]]; then travis_retry php vendor/bin/php-coveralls -v ; fi

notifications:
  email: false
